# Generated by Django 2.2.4 on 2019-11-24 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='caixa_geral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operacao', models.CharField(choices=[('1', 'Entrada'), ('2', 'Saida')], default=1, max_length=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('1', 'Dinheiro'), ('2', 'Cartao Debito'), ('3', 'Cartao Credito'), ('4', 'Boleto'), ('5', 'Transferencia')], default=1, max_length=1)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('id_operacao', models.CharField(max_length=200)),
                ('valor_operacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
